version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - "./target/keycloak-last-login.jar:/opt/keycloak/providers/keycloak-last-login.jar"
      - "./src/test/resources/realm-imports:/opt/keycloak/data/import"
    depends_on:
        postgres:
          condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:11.14-alpine
    command: postgres -c 'max_connections=300' -c 'shared_buffers=80MB'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U admin -d keycloak
      interval: 5s
      timeout: 3s
      retries: 10
