name: Maven CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
          cache: maven
      - name: Cache
        uses: ./.github/workflows/actions/caching
      - name: Build project with Maven
        run: mvn -B clean package
  matrix_compatability_test:
    runs-on: ubuntu-latest
    needs: build_and_test
    strategy:
      matrix:
        keycloak_version: [ 25.0.0, 25.0.1, 25.0.2, 25.0.4, 25.0.5, 25.0.6, 26.0.8, 26.1.0, 26.1.1, 26.1.2, latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Cache
        uses: ./.github/workflows/actions/caching
      - name: Run Tests for Matrix Versions
        run: mvn -B verify failsafe:verify -Dkeycloak.version=${{ matrix.keycloak_version }}
